server:
  port: 8080

spring:
  application:
    name: customer
  datasource:
    username: 'lippio'
    password: 'SpanishInquisition!'
    url: jdbc:postgresql://localhost:5432/customer

  jpa:
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    show-sql: 'true'
    hibernate:
      ddl-auto: update

logging:
  level:
    org:
      hibernate:
        type: TRACE
        SQL: DEBUG

#test purposes
management:
  endpoints:
    web:
      exposure:
        include: '*'

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
