server:
  port: 8200

spring:
  application:
    name: api-gateway
  zipkin:
    base-url: http://zipkin:9411
  cloud:
    gateway:
      routes:
        - id: customer
          uri: lb://CUSTOMER
          predicates:
            - Path=/api/v1/customers/**
  #        - id: fraud
  #          uri: lb://FRAUD  - based on eureka server
  #          predicates:
  #            - Path=/api/v1/fraud/** - which endpoints

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka
