server:
  port: 8100

spring:
  application:
    name: notification
  datasource:
    username: "lippio-mser"
    password: "password"
    url: jdbc:postgresql://postgres-new:5432/notification
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: 'create-drop'
    show-sql: true

  zipkin:
    base-url: http://zipkin:9411
  rabbitmq:
    addresses: rabbitmq:5672


eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka



# ITS NOT PART OF RABBIT MQ CONFIGURATION. ITS ONLY VALUE PARAMETERS FOR APPLICATION
rabbitmq:
  exchanges:
    # TOPIC EXCHANGE - gave it a name
    internal: internal.exchange
  queue:
    # NAME FOR QUEUE
    notification: notification.queue
  routing-keys:
    # HOW TITLE EXCHANGE FOR QUEUE (BINDING)
    internal-notification: internal.notification.routing-key
