server:
  port: 8081

spring:
  application:
    name: fraud
  datasource:
    username: 'lippio'
    password: 'SpanishInquisition!'
    url: jdbc:postgresql://localhost:5432/fraud
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    show-sql: 'true'
    hibernate:
      ddl-auto: update
